require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  RubyInterpreters:
    - ruby
    - macruby
    - rake
    - jruby
    - rbx
  # Include common Ruby source files.
  Include:
    - '**/*.rb'
    - '**/*.arb'
    - '**/*.axlsx'
    - '**/*.builder'
    - '**/*.fcgi'
    - '**/*.gemfile'
    - '**/*.gemspec'
    - '**/*.god'
    - '**/*.jb'
    - '**/*.jbuilder'
    - '**/*.mspec'
    - '**/*.opal'
    - '**/*.pluginspec'
    - '**/*.podspec'
    - '**/*.rabl'
    - '**/*.rake'
    - '**/*.rbuild'
    - '**/*.rbw'
    - '**/*.rbx'
    - '**/*.ru'
    - '**/*.ruby'
    - '**/*.spec'
    - '**/*.thor'
    - '**/*.watchr'
    - '**/.irbrc'
    - '**/.pryrc'
    - '**/.simplecov'
    - '**/buildfile'
    - '**/Appraisals'
    - '**/Berksfile'
    - '**/Brewfile'
    - '**/Buildfile'
    - '**/Capfile'
    - '**/Cheffile'
    - '**/Dangerfile'
    - '**/Deliverfile'
    - '**/Fastfile'
    - '**/*Fastfile'
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Jarfile'
    - '**/Mavenfile'
    - '**/Podfile'
    - '**/Puppetfile'
    - '**/Rakefile'
    - '**/rakefile'
    - '**/Snapfile'
    - '**/Steepfile'
    - '**/Thorfile'
    - '**/Vagabondfile'
    - '**/Vagrantfile'
  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
  # Default formatter will be used if no `-f/--format` option is given.
  DefaultFormatter: progress
  # Cop names are displayed in offense messages by default. Change behavior
  # by overriding DisplayCopNames, or by giving the `--no-display-cop-names`
  # option.
  DisplayCopNames: true
  # Style guide URLs are not displayed in offense messages by default. Change
  # behavior by overriding `DisplayStyleGuide`, or by giving the
  # `-S/--display-style-guide` option.
  DisplayStyleGuide: false
  # When specifying style guide URLs, any paths and/or fragments will be
  # evaluated relative to the base URL.
  StyleGuideBaseURL: https://rubystyle.guide
  # Extra details are not displayed in offense messages by default. Change
  # behavior by overriding ExtraDetails, or by giving the
  # `-E/--extra-details` option.
  ExtraDetails: false
  # Additional cops that do not reference a style guide rule may be enabled by
  # default. Change behavior by overriding `StyleGuideCopsOnly`, or by giving
  # the `--only-guide-cops` option.
  StyleGuideCopsOnly: false
  EnabledByDefault: true  
  # New cops introduced between major versions are set to a special pending status
  # and are not enabled by default with warning message.
  # Change this behavior by overriding either `NewCops: enable` or `NewCops: disable`.
  # When `NewCops` is `enable`, pending cops are enabled in bulk. Can be overridden by
  # the `--enable-pending-cops` command-line option.
  # When `NewCops` is `disable`, pending cops are disabled in bulk. Can be overridden by
  # the `--disable-pending-cops` command-line option.
  NewCops: pending
  # Enables the result cache if `true`. Can be overridden by the `--cache` command
  # line option.
  UseCache: true
  # Threshold for how many files can be stored in the result cache before some
  # of the files are automatically removed.
  MaxFilesInCache: 20000
  # The cache will be stored in "rubocop_cache" under this directory. If
  # CacheRootDirectory is ~ (nil), which it is by default, the root will be
  # taken from the environment variable `$XDG_CACHE_HOME` if it is set, or if
  # `$XDG_CACHE_HOME` is not set, it will be `$HOME/.cache/`.
  # The CacheRootDirectory can be overwritten by passing the `--cache-root` command
  # line option or by setting `$RUBOCOP_CACHE_ROOT` environment variable.
  CacheRootDirectory: ~
  # It is possible for a malicious user to know the location of RuboCop's cache
  # directory by looking at CacheRootDirectory, and create a symlink in its
  # place that could cause RuboCop to overwrite unintended files, or read
  # malicious input. If you are certain that your cache location is secure from
  # this kind of attack, and wish to use a symlinked cache location, set this
  # value to "true".
  AllowSymlinksInCacheRootDirectory: false  
  TargetRubyVersion: 2.7
  # Determines if a notification for extension libraries should be shown when
  # rubocop is run. Keys are the name of the extension, and values are an array
  # of gems in the Gemfile that the extension is suggested for, if not already
  # included.
  SuggestExtensions:
    rubocop-rails: [rails]
    rubocop-rspec: [rspec, rspec-rails]
    rubocop-minitest: [minitest]
    rubocop-sequel: [sequel]
    rubocop-rake: [rake]

Bundler/GemComment:
  Enabled: false   

Layout/DotPosition:
  EnforcedStyle: trailing
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
Layout/LineLength:
  Max: 95  
  IgnoredPatterns:
    - ^\s*it[ (]
    - ^\s*class
    - ^\s*module
    - ^\s*describe
    - ^\s*#
Layout/RedundantLineBreak:  
  Enabled: false
Layout/SingleLineBlockChain:
  Exclude:
    - "spec/**/*"
Layout/SpaceBeforeBlockBraces:
  Exclude:
    - "spec/**/*"
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/ConstantResolution:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
Metrics/MethodLength:
  Max: 20
Metrics/ModuleLength:
  Max: 200  

Rails/LexicallyScopedActionFilter:
  Enabled: false

RSpec/AlignLeftLetBrace:
  Enabled: false
RSpec/AlignRightLetBrace:
  Enabled: false
RSpec/ExampleLength:
  Max: 100
RSpec/ExpectChange:
  EnforcedStyle: block
RSpec/ImplicitSubject:
  Enabled: false  
RSpec/MessageExpectation:
  Enabled: false  
RSpec/MessageSpies:
  EnforcedStyle: receive
RSpec/MultipleExpectations:
  Max: 10 
RSpec/MultipleMemoizedHelpers:
  Max: 10   
RSpec/NestedGroups:
  Max: 5  

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:    
    - "config/**/*"
Style/ConstantVisibility:
  Enabled: false
Style/Copyright:
  Enabled: false
Style/Documentation:
  Exclude:
    - "db/migrate/**/*"
Style/DocumentationMethod:
  Exclude:
    - "db/migrate/**/*"
    - "spec/**/*"
Style/InlineComment:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Exclude:
    - "spec/**/*"
Style/NestedParenthesizedCalls:
  Exclude:
    - "spec/**/*" 
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '[]'
    '%q': '()'
    '%Q': '()'
    '%r': "''"
Style/RegexpLiteral:
  EnforcedStyle: percent_r
Style/StringHashKeys:
  Enabled: false    
Style/StringLiterals:
  EnforcedStyle: double_quotes

